### ISSUE TITLE
Add some Live Tiles to your launcher

### ISSUE THREAD

**Issue by mediaexplorer74** [binary-number/CarrierAppDeleter#1]
JP:
あなたはXamarin上のAndroid用のクールなランチャーアプリケーションを実装しました！ だから私は、この成功は、UNOの枠組みを通じて繰り返すことができることを理解していますか？ 私はメトロスタイルのライブタイルの長年のファンです。 Android Launcherの新しい反復での願いは、[Mosaic](https://github.com/mediaexplorer74/Mosaic) =のようないくつかのmetroシェルからのc＃コードを使用することです）

EN: 
Wow! You have implemented a cool launcher for Android on Xamarin! So I understand that this success can be repeated through the UNO framework? I'm a longtime fan of Metro style live tiles. The wish in the new iteration of Android Launcher is to use c# code from some metro shell like [Mosaic](https://github.com/mediaexplorer74/Mosaic) =)
Best,
MediaExplorer

_Big Microsoft Lumia smartphone's fanboy_

**Comment by actbit** [comment]
あなたが話しているのは[こちら](https://github.com/actbit/XamarinAndroidLauncher)のプロジェクトではありませんか？

こちらのプロジェクトは日本のスマホに標準搭載されている不要な消せないアプリを消すツールです

**Comment by mediaexplorer74** [comment]
ああ、残念ながら、私はあなたのソースコードの内容を見ませんでした（ロシア語では、Launcherという用語は、特別なソフトウェア/ツールではなく、ある種のカスタ 私はプロジェクトの名前に混乱していました。 そして私だけでなく、イギリス人のEmpyreal96も（彼はキャンセルされたWindows10Mobileモバイルシステムのファンでもあり、少なくともWindows PhoneのようなAndroidスマー.. 同時に、彼も私もKotlinやJavaプログラミング言語を知っていませんが、私たちはC＃しか知りません）

私はこのようなランチャーを意味しましたhttps://github.com/jetspiking/AndME 、クロスプラットフォームのXamarin frameworkとCプログラミング言語を使用して作成されます#

**Comment by mediaexplorer74** [comment]
痛い.. 私は最終的にあなたが私に書いたものを手に入れました。 はい、それはそれがある方法です。 私は間違いを犯し、間違ったリポジトリに問題を作成しました。 ごめんなさいお願いします!
